apiVersion: v1
kind: ConfigMap
metadata:
  name: cell-b-gateway-config
  namespace: cell-b
data:
  CELL_ID: "cell-b"
  PORT: "8020"
  ORDER_SERVICE_URL: "http://keda-add-on-http-interceptor-proxy.keda.svc.cluster.local:8080"
  ORDER_SERVICE_HOST: "cell-b-order-service.local"
  PAYMENT_SERVICE_URL: "http://keda-add-on-http-interceptor-proxy.keda.svc.cluster.local:8080"
  PAYMENT_SERVICE_HOST: "cell-b-payment-service.local"
  CELL_A_GATEWAY_URL: "http://keda-add-on-http-interceptor-proxy.keda.svc.cluster.local:8080"
  CELL_A_GATEWAY_HOST: "cell-a-gateway.local"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cell-b-gateway
  namespace: cell-b
  labels:
    cell: cell-b
    component: gateway
spec:
  replicas: 0  # KEDA will manage scaling
  selector:
    matchLabels:
      app: cell-b-gateway
  template:
    metadata:
      labels:
        app: cell-b-gateway
        cell: cell-b
        component: gateway
    spec:
      serviceAccountName: cell-b-service-account
      containers:
      - name: gateway 
        image: yashodperera/cell-b-gateway:latest
        ports:
        - containerPort: 8020
        envFrom:
        - configMapRef:
            name: cell-b-gateway-config
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8020
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8020
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: cell-b-gateway
  namespace: cell-b
  labels:
    cell: cell-b
    component: gateway
spec:
  selector:
    app: cell-b-gateway
  ports:
  - port: 8020
    targetPort: 8020
    name: http
  type: ClusterIP
---
apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: cell-b-gateway
  namespace: cell-b
spec:
  hosts:
    - cell-b-gateway.local
  scaleTargetRef:
    name: cell-b-gateway
    kind: Deployment
    apiVersion: apps/v1
    service: cell-b-gateway
    port: 8020
  replicas:
    min: 0
    max: 5
  scaledownPeriod: 30
  scalingMetric:
    requestRate:
      granularity: 1s
      window: 1m
      targetValue: 10 