apiVersion: v1
kind: ConfigMap
metadata:
  name: cell-b-payment-service-config
  namespace: cell-b
data:
  CELL_ID: "cell-b"
  PORT: "8022"
  ORDER_SERVICE_URL: "http://keda-add-on-http-interceptor-proxy.keda.svc.cluster.local:8080"
  ORDER_SERVICE_HOST: "cell-b-order-service.local"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cell-b-payment-service
  namespace: cell-b
  labels:
    cell: cell-b
    component: service
spec:
  replicas: 0  # KEDA will manage scaling
  selector:
    matchLabels:
      app: cell-b-payment-service
  template:
    metadata:
      labels:
        app: cell-b-payment-service
        cell: cell-b
        component: service
    spec:
      containers:
      - name: payment-service
        image: yashodperera/cell-b-payment-service:latest
        ports:
        - containerPort: 8022
        envFrom:
        - configMapRef:
            name: cell-b-payment-service-config
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8022
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8022
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: cell-b-payment-service
  namespace: cell-b
  labels:
    cell: cell-b
    component: service
spec:
  selector:
    app: cell-b-payment-service
  ports:
  - port: 8022
    targetPort: 8022
    name: http
  type: ClusterIP
---
apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: cell-b-payment-service
  namespace: cell-b
spec:
  hosts:
    - cell-b-payment-service.local
  scaleTargetRef:
    name: cell-b-payment-service
    kind: Deployment
    apiVersion: apps/v1
    service: cell-b-payment-service
    port: 8022
  replicas:
    min: 0
    max: 3
  scaledownPeriod: 60
  scalingMetric:
    requestRate:
      granularity: 1s
      window: 1m
      targetValue: 10 