apiVersion: v1
kind: ConfigMap
metadata:
  name: cell-b-order-service-config
  namespace: cell-b
data:
  CELL_ID: "cell-b"
  PORT: "8021"
  CELL_A_GATEWAY_URL: "http://cell-a-gateway.cell-a.svc.cluster.local:8010"
  PAYMENT_SERVICE_URL: "http://cell-b-payment-service.cell-b.svc.cluster.local:8022"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cell-b-order-service
  namespace: cell-b
  labels:
    cell: cell-b
    component: service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cell-b-order-service
  template:
    metadata:
      labels:
        app: cell-b-order-service
        cell: cell-b
        component: service
    spec:
      containers:
      - name: order-service
        image: yashodperera/cell-b-order-service:latest
        ports:
        - containerPort: 8021
        envFrom:
        - configMapRef:
            name: cell-b-order-service-config
        livenessProbe:
          httpGet:
            path: /health
            port: 8021
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8021
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: cell-b-order-service
  namespace: cell-b
  labels:
    cell: cell-b
    component: service
spec:
  selector:
    app: cell-b-order-service
  ports:
  - port: 8021
    targetPort: 8021
    name: http
  type: ClusterIP