apiVersion: v1
kind: ConfigMap
metadata:
  name: cell-b-gateway-config
  namespace: cell-b
data:
  CELL_ID: "cell-b"
  PORT: "8020"
  ORDER_SERVICE_URL: "http://cell-b-order-service.cell-b.svc.cluster.local:8021"
  PAYMENT_SERVICE_URL: "http://cell-b-payment-service.cell-b.svc.cluster.local:8022"
  CELL_A_GATEWAY_URL: "http://cell-a-gateway.cell-a.svc.cluster.local:8010"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cell-b-gateway
  namespace: cell-b
  labels:
    cell: cell-b
    component: gateway
  annotations:
    autoscaling.knative.dev/minScale: "0"
    autoscaling.knative.dev/maxScale: "10"
    autoscaling.knative.dev/target: "1"
    autoscaling.knative.dev/scaleDownDelay: "60s"
    autoscaling.knative.dev/scaleToZeroPodRetentionPeriod: "0s"
spec:
  template:
    metadata:
      labels:
        cell: cell-b
        component: gateway
      annotations:
        autoscaling.knative.dev/scaleDownDelay: "60s"
    spec:
      containers:
      - name: gateway 
        image: yashodperera/cell-b-gateway:latest
        ports:
        - containerPort: 8020
        envFrom:
        - configMapRef:
            name: cell-b-gateway-config
        livenessProbe:
          httpGet:
            path: /health
            port: 8020
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8020
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
