apiVersion: v1
kind: ConfigMap
metadata:
  name: cell-b-payment-service-config
  namespace: cell-b
data:
  CELL_ID: "cell-b"
  PORT: "8022"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cell-b-payment-service
  namespace: cell-b
  labels:
    cell: cell-b
    component: service
  annotations:
    autoscaling.knative.dev/minScale: "0"
    autoscaling.knative.dev/maxScale: "10"
    autoscaling.knative.dev/target: "1"
    autoscaling.knative.dev/scaleDownDelay: "60s"
    autoscaling.knative.dev/scaleToZeroPodRetentionPeriod: "0s"
spec:
  template:
    metadata:
      labels:
        cell: cell-b
        component: service
      annotations:
        autoscaling.knative.dev/scaleDownDelay: "60s"
    spec:
      containers:
      - name: payment-service
        image: yashodperera/cell-b-payment-service:latest
        ports:
        - containerPort: 8022
        envFrom:
        - configMapRef:
            name: cell-b-payment-service-config
        livenessProbe:
          httpGet:
            path: /health
            port: 8022
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8022
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"