apiVersion: v1
kind: ConfigMap
metadata:
  name: cell-a-gateway-config
  namespace: cell-a
data:
  CELL_ID: "cell-a"
  PORT: "8010"
  USER_SERVICE_URL: "http://cell-a-user-service.cell-a.svc.cluster.local:8011"
  PRODUCT_SERVICE_URL: "http://cell-a-product-service.cell-a.svc.cluster.local:8012"
  CELL_B_GATEWAY_URL: "http://cell-b-gateway.cell-b.svc.cluster.local:8020"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cell-a-gateway
  namespace: cell-a
  labels:
    cell: cell-a
    component: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cell-a-gateway
  template:
    metadata:
      labels:
        app: cell-a-gateway
        cell: cell-a
        component: gateway
    spec:
      serviceAccountName: cell-a-service-account
      initContainers:
      - name: prewarm-dependencies
        image: curlimages/curl:latest
        command: 
          - /bin/sh
          - -c
          - |
            echo "Pre-warming dependent services..."
            curl --max-time 30 --retry 5 --retry-delay 2 http://cell-a-user-service.cell-a:8011/health || echo "User service not ready"
            curl --max-time 30 --retry 5 --retry-delay 2 http://cell-a-product-service.cell-a:8012/health || echo "Product service not ready" 
            echo "Pre-warming completed"
      containers:
      - name: gateway
        image: yashodperera/cell-a-gateway
        ports:
        - containerPort: 8010
        envFrom:
        - configMapRef:
            name: cell-a-gateway-config
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: cell-a-gateway
  namespace: cell-a
  labels:
    cell: cell-a
    component: gateway
  annotations:
    scale-to-zero/scale-down-time: "10"
    scale-to-zero/reference: "deployment/cell-a/cell-a-gateway"
    scale-to-zero/dependencies: "cell-a-user-service,cell-a-product-service"
    scale-to-zero/cascade-scale: "true"
spec:
  selector:
    app: cell-a-gateway
  ports:
  - port: 8010
    targetPort: 8010
    name: http
  type: ClusterIP
