apiVersion: v1
kind: ConfigMap
metadata:
  name: cell-a-gateway-config
  namespace: cell-a
data:
  CELL_ID: "cell-a"
  PORT: "8010"
  USER_SERVICE_URL: "http://cell-a-user-service.cell-a.svc.cluster.local:8011"
  PRODUCT_SERVICE_URL: "http://cell-a-product-service.cell-a.svc.cluster.local:8012"
  CELL_B_GATEWAY_URL: "http://cell-b-gateway.cell-b.svc.cluster.local:8020"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cell-a-gateway
  namespace: cell-a
  labels:
    cell: cell-a
    component: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cell-a-gateway
  template:
    metadata:
      labels:
        app: cell-a-gateway
        cell: cell-a
        component: gateway
    spec:
      containers:
      - name: gateway
        image: yashodperera/cell-a-gateway
        ports:
        - containerPort: 8010
        envFrom:
        - configMapRef:
            name: cell-a-gateway-config
        livenessProbe:
          httpGet:
            path: /health
            port: 8010
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8010
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: cell-a-gateway
  namespace: cell-a
  labels:
    cell: cell-a
    component: gateway
spec:
  selector:
    app: cell-a-gateway
  ports:
  - port: 8010
    targetPort: 8010
    name: http
  type: ClusterIP
