apiVersion: v1
kind: ConfigMap
metadata:
  name: cell-a-user-service-config
  namespace: cell-a
data:
  CELL_ID: "cell-a"
  PORT: "8011"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cell-a-user-service
  namespace: cell-a
  labels:
    cell: cell-a
    component: service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cell-a-user-service
  template:
    metadata:
      labels:
        app: cell-a-user-service
        cell: cell-a
        component: service
    spec:
      containers:
      - name: user-service
        image: yashodperera/cell-a-user-service:latest
        ports:
        - containerPort: 8011
        envFrom:
        - configMapRef:
            name: cell-a-user-service-config
        livenessProbe:
          httpGet:
            path: /health
            port: 8011
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8011
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: cell-a-user-service
  namespace: cell-a
  labels:
    cell: cell-a
    component: service
spec:
  selector:
    app: cell-a-user-service
  ports:
  - port: 8011
    targetPort: 8011
    name: http
  type: ClusterIP