apiVersion: v1
kind: ConfigMap
metadata:
  name: cell-a-product-service-config
  namespace: cell-a
data:
  CELL_ID: "cell-a"
  PORT: "8012"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cell-a-product-service
  namespace: cell-a
  labels:
    cell: cell-a
    component: service
  annotations:
    autoscaling.knative.dev/minScale: "0"
    autoscaling.knative.dev/maxScale: "10"
    autoscaling.knative.dev/target: "1"
    autoscaling.knative.dev/scaleDownDelay: "60s"
    autoscaling.knative.dev/scaleToZeroPodRetentionPeriod: "0s"
spec:
  template:
    metadata:
      labels:
        cell: cell-a
        component: service
      annotations:
        autoscaling.knative.dev/scaleDownDelay: "60s"
    spec:
      containers:
      - name: product-service
        image: yashodperera/cell-a-product-service:latest
        ports:
        - containerPort: 8012
        envFrom:
        - configMapRef:
            name: cell-a-product-service-config
        livenessProbe:
          httpGet:
            path: /health
            port: 8012
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8012
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"