# Hybrid Scaling Configuration
# Gateways: KEDA HTTP scaling (scale to zero)
# Internal services: Always running (minimum 1 replica)

apiVersion: v1
kind: ConfigMap
metadata:
  name: cell-a-gateway-config-hybrid
  namespace: cell-a
data:
  CELL_ID: "cell-a"
  PORT: "8010"
  USER_SERVICE_URL: "http://cell-a-user-service.cell-a.svc.cluster.local:8011"
  PRODUCT_SERVICE_URL: "http://cell-a-product-service.cell-a.svc.cluster.local:8012"
  CELL_B_GATEWAY_URL: "http://keda-add-on-http-interceptor-proxy.keda.svc.cluster.local:8080"
  CELL_B_GATEWAY_HOST: "cell-b-gateway.local"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: cell-b-gateway-config-hybrid
  namespace: cell-b
data:
  CELL_ID: "cell-b"
  PORT: "8020"
  ORDER_SERVICE_URL: "http://cell-b-order-service.cell-b.svc.cluster.local:8021"
  PAYMENT_SERVICE_URL: "http://cell-b-payment-service.cell-b.svc.cluster.local:8022"
  CELL_A_GATEWAY_URL: "http://keda-add-on-http-interceptor-proxy.keda.svc.cluster.local:8080"
  CELL_A_GATEWAY_HOST: "cell-a-gateway.local"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: cell-b-order-service-config-hybrid
  namespace: cell-b
data:
  CELL_ID: "cell-b"
  PORT: "8021"
  CELL_A_GATEWAY_URL: "http://keda-add-on-http-interceptor-proxy.keda.svc.cluster.local:8080"
  CELL_A_GATEWAY_HOST: "cell-a-gateway.local"
  PAYMENT_SERVICE_URL: "http://cell-b-payment-service.cell-b.svc.cluster.local:8022"

---

# Update HTTPScaledObjects for internal services to have min 1 replica
apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: cell-a-user-service-hybrid
  namespace: cell-a
spec:
  hosts:
    - cell-a-user-service.local
  scaleTargetRef:
    name: cell-a-user-service
    kind: Deployment
    apiVersion: apps/v1
    service: cell-a-user-service
    port: 8011
  replicas:
    min: 1  # Always keep running
    max: 3
  scaledownPeriod: 60
  scalingMetric:
    requestRate:
      granularity: 1s
      window: 1m
      targetValue: 10

---

apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: cell-a-product-service-hybrid
  namespace: cell-a
spec:
  hosts:
    - cell-a-product-service.local
  scaleTargetRef:
    name: cell-a-product-service
    kind: Deployment
    apiVersion: apps/v1
    service: cell-a-product-service
    port: 8012
  replicas:
    min: 1  # Always keep running
    max: 3
  scaledownPeriod: 60
  scalingMetric:
    requestRate:
      granularity: 1s
      window: 1m
      targetValue: 10

---

apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: cell-b-order-service-hybrid
  namespace: cell-b
spec:
  hosts:
    - cell-b-order-service.local
  scaleTargetRef:
    name: cell-b-order-service
    kind: Deployment
    apiVersion: apps/v1
    service: cell-b-order-service
    port: 8021
  replicas:
    min: 1  # Always keep running
    max: 3
  scaledownPeriod: 60
  scalingMetric:
    requestRate:
      granularity: 1s
      window: 1m
      targetValue: 10

---

apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: cell-b-payment-service-hybrid
  namespace: cell-b
spec:
  hosts:
    - cell-b-payment-service.local
  scaleTargetRef:
    name: cell-b-payment-service
    kind: Deployment
    apiVersion: apps/v1
    service: cell-b-payment-service
    port: 8022
  replicas:
    min: 1  # Always keep running
    max: 3
  scaledownPeriod: 60
  scalingMetric:
    requestRate:
      granularity: 1s
      window: 1m
      targetValue: 10 