apiVersion: v1
kind: ConfigMap
metadata:
  name: cell-a-gateway-config
  namespace: cell-a
data:
  CELL_ID: "cell-a"
  PORT: "8010"
  USER_SERVICE_URL: "http://keda-add-on-http-interceptor-proxy.keda.svc.cluster.local:8080"
  USER_SERVICE_HOST: "cell-a-user-service.local"
  PRODUCT_SERVICE_URL: "http://keda-add-on-http-interceptor-proxy.keda.svc.cluster.local:8080"
  PRODUCT_SERVICE_HOST: "cell-a-product-service.local"
  CELL_B_GATEWAY_URL: "http://keda-add-on-http-interceptor-proxy.keda.svc.cluster.local:8080"
  CELL_B_GATEWAY_HOST: "cell-b-gateway.local"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cell-a-gateway
  namespace: cell-a
  labels:
    cell: cell-a
    component: gateway
spec:
  replicas: 0  # KEDA will manage scaling
  selector:
    matchLabels:
      app: cell-a-gateway
  template:
    metadata:
      labels:
        app: cell-a-gateway
        cell: cell-a
        component: gateway
    spec:
      serviceAccountName: cell-a-service-account
      initContainers:
      - name: prewarm-dependencies
        image: curlimages/curl:latest
        command: 
          - /bin/sh
          - -c
          - |
            echo "Pre-warming dependent services..."
            curl --max-time 30 --retry 5 --retry-delay 2 http://cell-a-user-service.cell-a:8011/health || echo "User service not ready"
            curl --max-time 30 --retry 5 --retry-delay 2 http://cell-a-product-service.cell-a:8012/health || echo "Product service not ready" 
            echo "Pre-warming completed"
      containers:
      - name: gateway
        image: yashodperera/cell-a-gateway
        ports:
        - containerPort: 8010
        envFrom:
        - configMapRef:
            name: cell-a-gateway-config
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8010
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8010
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: cell-a-gateway
  namespace: cell-a
  labels:
    cell: cell-a
    component: gateway
spec:
  selector:
    app: cell-a-gateway
  ports:
  - port: 8010
    targetPort: 8010
    name: http
  type: ClusterIP
---
apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: cell-a-gateway
  namespace: cell-a
spec:
  hosts:
    - cell-a-gateway.local
  scaleTargetRef:
    name: cell-a-gateway
    kind: Deployment
    apiVersion: apps/v1
    service: cell-a-gateway
    port: 8010
  replicas:
    min: 0
    max: 5
  scaledownPeriod: 30
  scalingMetric:
    requestRate:
      granularity: 1s
      window: 1m
      targetValue: 10 