apiVersion: v1
kind: ConfigMap
metadata:
  name: cell-a-user-service-config
  namespace: cell-a
data:
  CELL_ID: "cell-a"
  PORT: "8011"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cell-a-user-service
  namespace: cell-a
  labels:
    cell: cell-a
    component: service
spec:
  replicas: 0  # KEDA will manage scaling
  selector:
    matchLabels:
      app: cell-a-user-service
  template:
    metadata:
      labels:
        app: cell-a-user-service
        cell: cell-a
        component: service
    spec:
      containers:
      - name: user-service
        image: yashodperera/cell-a-user-service:latest
        ports:
        - containerPort: 8011
        envFrom:
        - configMapRef:
            name: cell-a-user-service-config
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8011
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8011
          initialDelaySeconds: 5
          periodSeconds: 5
--- 
apiVersion: v1
kind: Service
metadata:
  name: cell-a-user-service
  namespace: cell-a
  labels:
    cell: cell-a
    component: service
spec:
  selector:
    app: cell-a-user-service
  ports:
  - port: 8011
    targetPort: 8011
    name: http
  type: ClusterIP
---
apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: cell-a-user-service
  namespace: cell-a
spec:
  hosts:
    - cell-a-user-service.local
  scaleTargetRef:
    name: cell-a-user-service
    kind: Deployment
    apiVersion: apps/v1
    service: cell-a-user-service
    port: 8011
  replicas:
    min: 0
    max: 3
  scaledownPeriod: 60
  scalingMetric:
    requestRate:
      granularity: 1s
      window: 1m
      targetValue: 10 